name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - run: sudo apt update && sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
    - name: Clippy for bevy_rapier2d
      run: cargo clippy --verbose -p bevy_rapier2d
    - name: Clippy for bevy_rapier3d
      run: cargo clippy --verbose -p bevy_rapier3d
    - name: Clippy for bevy_rapier2d (debug-render, simd, serde)
      run: cargo clippy --verbose -p bevy_rapier2d --features debug-render,simd-stable,serde-serialize
    - name: Clippy for bevy_rapier3d (debug-render, simd, serde)
      run: cargo clippy --verbose -p bevy_rapier3d --features debug-render,simd-stable,serde-serialize
    - name: Test for bevy_rapier2d
      run: cargo test --verbose -p bevy_rapier2d
    - name: Test for bevy_rapier3d
      run: cargo test --verbose -p bevy_rapier3d
  test-wasm:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
      - name: Clippy bevy_rapier2d
        run: cd bevy_rapier2d && cargo clippy --verbose --features wasm-bindgen --target wasm32-unknown-unknown
      - name: Clippy bevy_rapier3d
        run: cd bevy_rapier3d && cargo clippy --verbose --features wasm-bindgen --target wasm32-unknown-unknown
